package com.tuan.inventory.dao.data;

import java.math.BigDecimal;

import com.tuan.core.common.lang.TuanBaseDO;
/**
 * 订单的商品信息，注：订单的商品信息基本都是从购物车所对应的表中取来的。
 * <ul>
 * <li></li>
 * <li>创建人： 相磊</li>
 * <li>创建时间: Jun 17, 2010 4:46:15 PM</li>
 * </ul>
 */
public class OrderGoodsDO extends TuanBaseDO{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.rec_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private Integer recId;//订单商品信息自增id'

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.order_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private Integer orderId;//订单商品信息对应的详细信息id，取值order_info的order_id',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.goods_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private Integer goodsId;//商品的的id，取值表ecs_goods 的goods_id',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.goods_name
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private String goodsName;//商品的名称，取值表ecs_goods ',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.goods_sn
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private String goodsSn;//商品的唯一货号，取值ecs_goods '

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.goods_number
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private int goodsNumber;//商品的购买数量',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.market_price
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private BigDecimal marketPrice;//商品的市场售价，取值ecs_goods ',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.goods_price
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private BigDecimal goodsPrice;//商品的本店售价，取值ecs_goods ',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.send_number
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private int sendNumber;//当不是实物时，是否已发货，0，否；1，是',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.is_real
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private int isReal;//是否是实物，0，否；1，是；取值ecs_goods ',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.extension_code
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private String extensionCode;//商品的扩展属性，比如像虚拟卡。取值ecs_goods ',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.parent_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private Integer parentId;//FIXME:父商品id，取值于ecs_cart的parent_id；如果有该值则是值多代表的物品的配件',?????????????????????

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.is_gift
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private int isGift;//是否参加优惠活动，0，否；其他，取值于ecs_cart 的is_gift，跟其一样，是参加的优惠活动的id',


    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.goods_attr_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private String goodsAttrId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column jeehe_order_goods.goods_attr
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    private String goodsAttr;//'购买该商品时所选择的属性；',


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.rec_id
     *
     * @return the value of jeehe_order_goods.rec_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.rec_id
     *
     * @param recId the value for jeehe_order_goods.rec_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.order_id
     *
     * @return the value of jeehe_order_goods.order_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.order_id
     *
     * @param orderId the value for jeehe_order_goods.order_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.goods_id
     *
     * @return the value of jeehe_order_goods.goods_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.goods_id
     *
     * @param goodsId the value for jeehe_order_goods.goods_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.goods_name
     *
     * @return the value of jeehe_order_goods.goods_name
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.goods_name
     *
     * @param goodsName the value for jeehe_order_goods.goods_name
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.goods_sn
     *
     * @return the value of jeehe_order_goods.goods_sn
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.goods_sn
     *
     * @param goodsSn the value for jeehe_order_goods.goods_sn
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.goods_number
     *
     * @return the value of jeehe_order_goods.goods_number
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public int getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.goods_number
     *
     * @param goodsNumber the value for jeehe_order_goods.goods_number
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setGoodsNumber(int goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.market_price
     *
     * @return the value of jeehe_order_goods.market_price
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.market_price
     *
     * @param marketPrice the value for jeehe_order_goods.market_price
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.goods_price
     *
     * @return the value of jeehe_order_goods.goods_price
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.goods_price
     *
     * @param goodsPrice the value for jeehe_order_goods.goods_price
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.send_number
     *
     * @return the value of jeehe_order_goods.send_number
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public int getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.send_number
     *
     * @param sendNumber the value for jeehe_order_goods.send_number
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setSendNumber(int sendNumber) {
        this.sendNumber = sendNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.is_real
     *
     * @return the value of jeehe_order_goods.is_real
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public int getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.is_real
     *
     * @param isReal the value for jeehe_order_goods.is_real
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setIsReal(int isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.extension_code
     *
     * @return the value of jeehe_order_goods.extension_code
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.extension_code
     *
     * @param extensionCode the value for jeehe_order_goods.extension_code
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.parent_id
     *
     * @return the value of jeehe_order_goods.parent_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.parent_id
     *
     * @param parentId the value for jeehe_order_goods.parent_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.is_gift
     *
     * @return the value of jeehe_order_goods.is_gift
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public int getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.is_gift
     *
     * @param isGift the value for jeehe_order_goods.is_gift
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setIsGift(int isGift) {
        this.isGift = isGift;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.goods_attr_id
     *
     * @return the value of jeehe_order_goods.goods_attr_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public String getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.goods_attr_id
     *
     * @param goodsAttrId the value for jeehe_order_goods.goods_attr_id
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setGoodsAttrId(String goodsAttrId) {
        this.goodsAttrId = goodsAttrId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column jeehe_order_goods.goods_attr
     *
     * @return the value of jeehe_order_goods.goods_attr
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column jeehe_order_goods.goods_attr
     *
     * @param goodsAttr the value for jeehe_order_goods.goods_attr
     *
     * @abatorgenerated Wed Jun 16 21:21:40 CST 2010
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr;
    }
}